### ISSUE TITLE
[FIREBASE] Send to webhook fails

### ISSUE THREAD

**Issue by lupodellasleppa** [lupodellasleppa/raspb-scripts#12]
```
nov 27 08:24:27 raspberrypi python3[330]: Exception in thread thermostat-loop:
nov 27 08:24:27 raspberrypi python3[330]: Traceback (most recent call last):
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
nov 27 08:24:27 raspberrypi python3[330]:     chunked=chunked)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
nov 27 08:24:27 raspberrypi python3[330]:     six.raise_from(e, None)
nov 27 08:24:27 raspberrypi python3[330]:   File "<string>", line 3, in raise_from
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
nov 27 08:24:27 raspberrypi python3[330]:     httplib_response = conn.getresponse()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
nov 27 08:24:27 raspberrypi python3[330]:     response.begin()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/http/client.py", line 306, in begin
nov 27 08:24:27 raspberrypi python3[330]:     version, status, reason = self._read_status()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
nov 27 08:24:27 raspberrypi python3[330]:     raise RemoteDisconnected("Remote end closed connection without"
nov 27 08:24:27 raspberrypi python3[330]: http.client.RemoteDisconnected: Remote end closed connection without response
nov 27 08:24:27 raspberrypi python3[330]: During handling of the above exception, another exception occurred:
nov 27 08:24:27 raspberrypi python3[330]: Traceback (most recent call last):
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
nov 27 08:24:27 raspberrypi python3[330]:     timeout=timeout
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
nov 27 08:24:27 raspberrypi python3[330]:     _stacktrace=sys.exc_info()[2])
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
nov 27 08:24:27 raspberrypi python3[330]:     raise six.reraise(type(error), error, _stacktrace)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/six.py", line 702, in reraise
nov 27 08:24:27 raspberrypi python3[330]:     raise value.with_traceback(tb)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
nov 27 08:24:27 raspberrypi python3[330]:     chunked=chunked)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
nov 27 08:24:27 raspberrypi python3[330]:     six.raise_from(e, None)
nov 27 08:24:27 raspberrypi python3[330]:   File "<string>", line 3, in raise_from
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
nov 27 08:24:27 raspberrypi python3[330]:     httplib_response = conn.getresponse()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
nov 27 08:24:27 raspberrypi python3[330]:     response.begin()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/http/client.py", line 306, in begin
nov 27 08:24:27 raspberrypi python3[330]:     version, status, reason = self._read_status()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
nov 27 08:24:27 raspberrypi python3[330]:     raise RemoteDisconnected("Remote end closed connection without"
nov 27 08:24:27 raspberrypi python3[330]: urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
nov 27 08:24:27 raspberrypi python3[330]: During handling of the above exception, another exception occurred:
nov 27 08:24:27 raspberrypi python3[330]: Traceback (most recent call last):
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
nov 27 08:24:27 raspberrypi python3[330]:     self.run()
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/threading.py", line 865, in run
nov 27 08:24:27 raspberrypi python3[330]:     self._target(*self._args, **self._kwargs)
nov 27 08:24:27 raspberrypi python3[330]:   File "/home/pi/thermostat-py/src/main.py", line 542, in run_thermostat
nov 27 08:24:27 raspberrypi python3[330]:     asyncio.run(thermostat.loop())
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
nov 27 08:24:27 raspberrypi python3[330]:     return loop.run_until_complete(main)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
nov 27 08:24:27 raspberrypi python3[330]:     return future.result()
nov 27 08:24:27 raspberrypi python3[330]:   File "/home/pi/thermostat-py/src/main.py", line 378, in loop
nov 27 08:24:27 raspberrypi python3[330]:     last_msg = self.db.child("webhook").push(payload)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/pyrebase/pyrebase.py", line 292, in push
nov 27 08:24:27 raspberrypi python3[330]:     request_object = self.requests.post(request_ref, headers=headers, data=json.dumps(data, **json_kwargs).encode("utf-8"))
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 578, in post
nov 27 08:24:27 raspberrypi python3[330]:     return self.request('POST', url, data=data, json=json, **kwargs)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 530, in request
nov 27 08:24:27 raspberrypi python3[330]:     resp = self.send(prep, **send_kwargs)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 643, in send
nov 27 08:24:27 raspberrypi python3[330]:     r = adapter.send(request, **kwargs)
nov 27 08:24:27 raspberrypi python3[330]:   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 498, in send
nov 27 08:24:27 raspberrypi python3[330]:     raise ConnectionError(err, request=request)
nov 27 08:24:27 raspberrypi python3[330]: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by lupodellasleppa** [comment]
all sends to Firebase have been trapped in 4e0d34496116bfb9b48354615fc4066449ccc1b1
